# py-temp-fork-pub-merge_no_docker-def.yaml
# This is a template and should not be changed unless you are familiar with the
# reusable GitHub Actions strategy of the company.
name: Python Template Merge no Docker with Local Fork

on:
  push:

jobs:
  py-temp-fork-pub-merge_no_docker-def:
    permissions:
      id-token: write
      contents: write
    #    if: github.event.pull_request.merged == true
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-wf-fork-pub-merge_no_docker-def.yaml@master
    # with:
      # run_deploy: ${{ startsWith(github.ref, 'refs/tags/') == true }}
    # secrets: inherit
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
      INSTALLER_USERID:          ${{vars.INSTALLER_USERID }}
      INSTALLER_PWD:             ${{secrets.INSTALLER_PWD }}
      MYSQL_DATABASE:            ${{vars.MYSQL_DATABASE }}
      MYSQL_HOST:                ${{vars.MYSQL_HOST }}
      MYSQL_PASSWORD:            ${{secrets.MYSQL_PASSWORD}}
      MYSQL_ROOT_PASSWORD:       ${{secrets.MYSQL_ROOT_PASSWORD}}
      MYSQL_TCP_PORT:             ${{vars.MYSQL_TCP_PORT }}
      MYSQL_USER:                ${{vars.MYSQL_USER}}
      PROJECT_NAME:               ${{vars.PROJECT_NAME }}
      RELEASE_EMAIL_USER:        ${{vars.RELEASE_EMAIL_USER }}
      RELEASE_EMAIL_PASSWORD:    ${{secrets.RELEASE_EMAIL_PASSWORD }}
      VENV_ENVIRONMENT:          ${{vars.VENV_ENVIRONMENT }}
